//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingMobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mobile()
        {
            this.MobileDetails = new HashSet<MobileDetail>();
        }
    
        public int slNo { get; set; }
        public string MobileName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string url { get; set; }
        public string Description { get; set; }
        public string ZoomUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileDetail> MobileDetails { get; set; }
    }
}
